name: kthcloud-ci
"on":
  push:
    branches:
    - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cloud.cbh.kth.se
        username: robot$deploy-0819b9b6-e000-4a62-87c0-bc0a095a3c28+wikipedia-visualizer-backend
        password: Zo65M8fkUCu1flodh4bkpak3poteF5fs
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: registry.cloud.cbh.kth.se/deploy-0819b9b6-e000-4a62-87c0-bc0a095a3c28/wikipedia-visualizer-backend
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cloud.cbh.kth.se
        username: robot$deploy-0819b9b6-e000-4a62-87c0-bc0a095a3c28+wikipedia-visualizer-frontend
        password: 606D1lTEWoN1wClov4vEjX7F2UwslBZ0
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: registry.cloud.cbh.kth.se/deploy-0819b9b6-e000-4a62-87c0-bc0a095a3c28/wikipedia-visualizer-frontend